// examples/angular-furigana/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  text = '秋[あき]の 田[た]の　　かりほの 庵[いほ]の　　苫[とま]をあらみ';
  alt = 'わが 衣手[ころもで]は　　露[つゆ]にぬれつつ';

  changeText() {
    const temp = this.text
    this.text = this.alt
    this.alt = temp
  }
}

<img
  width="200"
  alt="Angular Logo"
  src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyNTAgMjUwIj4KICAgIDxwYXRoIGZpbGw9IiNERDAwMzEiIGQ9Ik0xMjUgMzBMMzEuOSA2My4ybDE0LjIgMTIzLjFMMTI1IDIzMGw3OC45LTQzLjcgMTQuMi0xMjMuMXoiIC8+CiAgICA8cGF0aCBmaWxsPSIjQzMwMDJGIiBkPSJNMTI1IDMwdjIyLjItLjFWMjMwbDc4LjktNDMuNyAxNC4yLTEyMy4xTDEyNSAzMHoiIC8+CiAgICA8cGF0aCAgZmlsbD0iI0ZGRkZGRiIgZD0iTTEyNSA1Mi4xTDY2LjggMTgyLjZoMjEuN2wxMS43LTI5LjJoNDkuNGwxMS43IDI5LjJIMTgzTDEyNSA1Mi4xem0xNyA4My4zaC0zNGwxNy00MC45IDE3IDQwLjl6IiAvPgogIDwvc3ZnPg=="
/>
<h1>
  <wc-furigana id="furigana" value="{{ text }}"></wc-furigana>
</h1>
<div>
  <button (click)="changeText()">Change text</button>
</div>

// examples/react-furigana/src/App.js
import React from 'react';
import logo from './logo.svg';
import './App.css';

class Text extends React.Component {
  constructor(props) {
    super(props);
    this.changeText = this.changeText.bind(this);
    this.state = {
      foo: 'bar',
      text: '秋[あき]の 田[た]の　　かりほの 庵[いほ]の　　苫[とま]をあらみ',
      alt: 'わが 衣手[ころもで]は　　露[つゆ]にぬれつつ'
    };
  }

  changeText() {
    this.setState({
      text: this.state.alt,
      alt: this.state.text
    });
  }

  render () {
    return (
      <div>
        <h1>
          <wc-furigana value={ this.state.text }></wc-furigana>
        </h1>
        <p>
          <button onClick={ this.changeText }>Change text</button>
        </p>
      </div>
    );
  }
}

function App() {
  return (
    <div className="App">
      <header className="App-header">
        <img src={logo} className="App-logo" alt="logo" />
        <Text />
      </header>
    </div>
  );
}

export default App;
